#!/usr/bin/env node

const fs = require('fs');
const { join } = require('path');
const wikiDir = join(__dirname, '../wiki');

function sortArticles(article1, article2) {
    return (article2[0].match(/\//g) || []).length
         - (article1[0].match(/\//g) || []).length;
}

function articleInfo() {
    return {
        // 'Current_Full_Path': ['New title', 'New_local_path']
        // New_local_path only needs to be included if it can't be inferred from New title
        //
        // excluding Tournaments/, Contests/, Main Page
        'Accuracy': ['Accuracy'],
        'Article_Styling_Criteria': ['Article styling criteria'],
        'BanchoBot': ['BanchoBot'],
        'BBCode': ['BBCode'],
        'Beatmap_Discussion': ['Beatmap discussion'],
        'Beatmap_Editor': ['Beatmap editor'],
        'Beatmap_Editor/AiMod': ['AiMod'],
        'Beatmap_Editor/Beat_Snap_Divisor': ['Beat snap divisor'],
        'Beatmap_Editor/Compose': ['Compose'],
        'Beatmap_Editor/Design': ['Design'],
        'Beatmap_Editor/Distance_Snap': ['Distance snap'],
        'Beatmap_Editor/Kiai_Time': ['Kiai time'],
        'Beatmap_Editor/Menu': ['Menu'],
        'Beatmap_Editor/SB_Load': ['SB load'],
        'Beatmap_Editor/Song_Setup': ['Song setup'],
        'Beatmap_Editor/Timelines': ['Timelines'],
        'Beatmap_Editor/Timing': ['Timing'],
        'Beatmap_ranking_procedure': ['Beatmap ranking procedure'],
        'Beatmapping': ['Beatmapping'],
        'Beatmaps': ['Beatmaps'],
        'Beatmaps/History_of_Loved': ['History of Loved'],
        'Beatmaps/Packs': ['Packs'],
        'Beatmaps/Title_Text': ['Title text'],
        'Brand_identity_guidelines': ['Brand identity guidelines'],
        'Chat_Console': ['Chat console'],
        'Contests': ['Contests'],
        'Difficulties': ['Difficulties'],
        'Disambiguation': ['Disambiguation'],
        'Disambiguation/Bancho': ['Bancho'],
        'Disambiguation/Easy': ['Easy'],
        'Disambiguation/EZ': ['EZ'],
        'Disambiguation/Mod': ['Mod'],
        'Do_you_really_want_to_ask_peppy': ['Do you really want to ask peppy?', 'Do_you_really_want_to_ask_peppy'],
        'FAQ': ['FAQ'],
        'Featured_Artists': ['Featured artists'],
        'Game_Modes': ['Game modes'],
        'Game_Modes/osu!': ['osu!'],
        'Game_Modes/osu!catch': ['osu!catch'],
        'Game_Modes/osu!mania': ['osu!mania'],
        'Game_Modes/osu!taiko': ['osu!taiko'],
        'Game_Modifiers': ['Game modifiers'],
        'Game_Modifiers/Summary': ['Summary'],
        'Glossary': ['Glossary'],
        'Guides': ['Guides'],
        'Guides/Adding_Custom_Hitsounds': ['Adding custom hitsounds'],
        'Guides/Audio_Editing': ['Audio editing'],
        "Guides/Beginner's_Tutorial": ['Beginner', "Beginner's_tutorial"],
        'Guides/BSS_Issues': ['BSS issues'],
        'Guides/Changing_the_Artist_or_Title': ["Changing the map's artist or title", 'Changing_the_artist_or_title'],
        'Guides/Collab_Information': ['Collab information'],
        'Guides/Compressing_Files': ['Compressing files'],
        'Guides/Cropping_with_Complex_Backgrounds': ['Cropping with complex backgrounds'],
        'Guides/Cropping_with_Simple_Backgrounds': ['Cropping with simple backgrounds'],
        'Guides/Custom_Hitsound_Library': ['Custom hitsound library'],
        'Guides/Custom_Sample_Overrides': ['Custom sample overrides'],
        'Guides/Discord_Rich_Presence': ['Discord Rich Presence'],
        'Guides/Getting_Songs_From_Video_Games': ['Getting songs from video games'],
        'Guides/Getting_Your_Map_Modded': ['Getting your map modded'],
        'Guides/How_to_Play_osu!mania': ['How to play osu!mania'],
        'Guides/How_to_Time_Songs': ['How to time songs'],
        'Guides/How_to_Use_the_Offset_Wizard': ['How to use the offset wizard'],
        'Guides/Live_Streaming_osu!': ['Live streaming osu!'],
        'Guides/Making_Properly_Centered_Spinners': ['Making properly centered spinners'],
        'Guides/Music_Theory': ['Music theory'],
        'Guides/OpenGL_Support_Issues': ['OpenGL support issues'],
        'Guides/osu!mania_Mapping_Guide': ['osu!mania mapping guide'],
        'Guides/Recording_osu!': ['Recording osu!'],
        'Guides/Searching_and_Downloading_Beatmaps': ['Searching and downloading beatmaps'],
        'Guides/Setting_the_Offset_on_the_Correct_Beat': ['Setting the offset on the correct beat'],
        'Guides/Starting_a_Beatmap_Project': ['Starting a beatmap project'],
        'Guides/Tablet_Purchase': ['Tablet purchase'],
        'Guides/Tips_and_Tricks_on_Skill_Improvement': ['Tips and tricks on skill improvement'],
        'Guides/Videos_From_Youtube': ['Videos from YouTube'],
        'Help_Centre': ['Help centre'],
        'Help_Centre/Account_Restrictions': ['Account restrictions'],
        'History_of_osu!': ['History of osu!'],
        'History_of_osu!/2007': ['2007'],
        'History_of_osu!/2008': ['2008'],
        'History_of_osu!/2009': ['2009'],
        'History_of_osu!/2010': ['2010'],
        'History_of_osu!/2011': ['2011'],
        'History_of_osu!/2012': ['2012'],
        'History_of_osu!/2013': ['2013'],
        'History_of_osu!/2014': ['2014'],
        'History_of_osu!/2015': ['2015'],
        'History_of_osu!/2016': ['2016'],
        'History_of_osu!/2017': ['2017'],
        'History_of_osu!/2018': ['2018'],
        'History_of_osu!/osu!_wiki': ['osu! wiki'],
        'Hit_Objects': ['Hit objects'],
        'How_You_Can_Help!': ['How you can help!'],
        'Installation': ['Installation'],
        'Installation/macOS': ['macOS'],
        'Interface': ['Interface'],
        'Internet_Relay_Chat': ['What is Internet Relay Chat?', 'Internet_Relay_Chat'],
        'Legal': ['Legal'],
        'Legal/Copyright': ['osu! copyright policy', 'Copyright'],
        'Legal/Music_Licensing': ['osu! music licensing', 'Music_licensing'],
        'Legal/Privacy': ['osu! privacy policy', 'Privacy'],
        'Legal/Terms': ['osu! terms of service', 'Terms'],
        'Mapping_Techniques': ['Mapping techniques'],
        'Mapping_Techniques/Basics': ['Basics'],
        'Mapping_Techniques/Formations': ['Formations'],
        'Mapping_Techniques/Jumps': ['Jumps'],
        'Mapping_Techniques/Making_Good_Sliders': ['Making good sliders'],
        'Mapping_Techniques/Rhythm': ['Rhythm'],
        'Mapping_Techniques/Sliders': ['Sliders'],
        'Mapping_Techniques/Spinners': ['Spinners'],
        'Mapping_Techniques/Unrankable': ['Unrankable'],
        'Mascots': ['Mascots'],
        'Mascots/Gallery': ['Gallery'],
        'Medals': ['Medals'],
        'Medals/Beatmap_Packs_0916': ['Beatmap packs 0916'],
        'Modding': ['Modding'],
        'Multi': ['Multi'],
        'News_Styling_Criteria': ['News styling criteria'],
        'Options': ['Options'],
        'Options/Keyboard_Bindings': ['Keyboard bindings'],
        'Options/Offset_Wizard': ['Offset wizard'],
        'Organisations': ['Organisations'],
        'Organisations/osu!_UCI': ['osu! UCI'],
        'osu!_File_Formats': ['osu! file formats'],
        'osu!_File_Formats/Db_(file_format)': ['.db (file format)', 'db_(file_format)'],
        'osu!_File_Formats/Osb_(file_format)': ['.osb (file format)', 'osb_(file_format)'],
        'osu!_File_Formats/Osk_(file_format)': ['.osk (file format)', 'osk_(file_format)'],
        'osu!_File_Formats/Osr_(file_format)': ['.osr (file format)', 'osr_(file_format)'],
        'osu!_File_Formats/Osu_(file_format)': ['.osu (file format)', 'osu_(file_format)'],
        'osu!_File_Formats/Osz_(file_format)': ['.osz (file format)', 'osz_(file_format)'],
        'osu!_Program_Files': ['osu! program files'],
        'osu!_Program_Files/User_Configuration_File': ['User configuration file'],
        'osu!_wiki_Contribution_Guide': ['osu! wiki contribution guide'],
        'osu!_wiki_Contribution_Guide/Common_Issues': ['Common issues'],
        'osu!_wiki_Contribution_Guide/GitHub_Desktop': ['GitHub Desktop'],
        'osu!_wiki_Contribution_Guide/GitHub_Web_Interface': ['GitHub web interface'],
        'osu!academy': ['osu!academy'],
        'osu!api': ['osu!api'],
        'osu!mapping': ['osu!mapping'],
        'osu!stream': ['osu!stream'],
        'osu!stream/Song_List': ['osu!stream/Song list', 'Song_list'],
        'osu!supporter': ['osu!supporter'],
        'osu!talk': ['osu!talk'],
        'osu!tourney': ['osu!tourney'],
        'osu!tourney/Multiplayer_Usage': ['Multiplayer usage'],
        'osu!tourney/Prizes': ['Prizes'],
        'osu!tourney/Setup': ['Setup'],
        'osu!tourney/Skinning': ['Skinning'],
        'osu!tourney/Spectator_Usage': ['Spectator usage'],
        'osu!tourney/Tournament_Management_Commands': ['Tournament management commands'],
        'osu!tourney/Troubleshooting': ['Troubleshooting'],
        'People': ['People'],
        'People/Community_Contributors': ['Community Contributors'],
        'People/The_Team': ['The Team'],
        'People/The_Team/Beatmap_Nominators': ['Beatmap Nominators'],
        'People/The_Team/Beatmap_Nominators/Beatmap_Veto': ['Beatmap veto'],
        'People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator': ['Becoming a Beatmap Nominator'],
        'People/The_Team/Beatmap_Nominators/General_Information': ['General information for Beatmap Nominators', 'General_information'],
        'People/The_Team/Beatmap_Nominators/Rules': ['Rules'],
        'People/The_Team/Developers': ['Developers'],
        'People/The_Team/Global_Moderation_Team': ['Global Moderation Team'],
        'People/The_Team/Nomination_Assessment_Team': ['Nomination Assessment Team'],
        'People/The_Team/osu!_Alumni': ['osu! Alumni'],
        'People/The_Team/Project_Loved_Team': ['Project Loved Team'],
        'People/The_Team/Support_Team': ['Support Team'],
        'People/Users_with_unique_titles': ['Users with unique titles'],
        'Performance_Points': ['Performance points'],
        'Performance_Points/ppv1': ['ppv1'],
        'Performance_Troubleshooting': ['osu! performance troubleshooting', 'Performance_troubleshooting'],
        'Play_Styles': ['Play styles'],
        'Project_Loved': ['Project Loved'],
        'Projects': ['Projects'],
        'Quality_Assurance_Team_Blog': ['Quality Assurance Team Blog'],
        'Ranking_Criteria': ['Ranking criteria'],
        'Ranking_Criteria/Difficulty_Naming': ['Difficulty naming'],
        'Ranking_Criteria/osu!': ['osu! ranking criteria', 'osu!'],
        'Ranking_Criteria/osu!catch': ['osu!catch ranking criteria', 'osu!catch'],
        'Ranking_Criteria/osu!mania': ['osu!mania ranking criteria', 'osu!mania'],
        'Ranking_Criteria/osu!taiko': ['osu!taiko ranking criteria', 'osu!taiko'],
        'Ranking_Criteria/Scaling_BPM': ['Scaling BPM on the ranking criteria', 'Scaling_BPM'],
        'Ranking_Criteria/Skin_Set_List': ['Skin set list'],
        'Ranking_Criteria/Timing_Songs_With_8-Signatures': ['Timing songs with #/8-signatures', 'Timing_songs_with_8-signatures'],
        'Registration': ['Registration'],
        'Replay': ['Replay'],
        'Reporting_Bad_Behaviour': ['Reporting bad behaviour'],
        'Reporting_Bad_Behaviour/Handling_Foul_Play': ['Handling foul play'],
        'Rules': ['Rules'],
        'Rules/Code_of_Conduct_for_Modding_and_Mapping': ['Code of conduct for modding and mapping'],
        'Rules/Song_Content_Rules': ['Song content rules'],
        'Rules/Visual_Content_Considerations': ['Visual content considerations'],
        'Score': ['Score'],
        'Score/ScoreV1': ['ScoreV1'],
        'Shortcut_key_reference': ['Shortcut key reference'],
        'Sitemap': ['Sitemap'],
        'Skinning_Tutorial': ['Skinning tutorial'],
        'Skinning_Tutorial/Interface': ['Skinning tutorial (interface)', 'Interface'],
        'Skinning_Tutorial/osu!': ['Skinning tutorial (osu!)', 'osu!'],
        'Skinning_Tutorial/osu!catch': ['osu!catch'],
        'Skinning_Tutorial/osu!mania': ['osu!mania'],
        'Skinning_Tutorial/osu!taiko': ['Skinning tutorial (osu!taiko)', 'osu!taiko'],
        'Skinning_Tutorial/skin.ini': ['skin.ini'],
        'Skinning': ['Skinning'],
        'Skinning/FAQ': ['FAQ'],
        'Skinning/Guides_and_Important_Threads': ['Guides and important threads'],
        'Skinning/History': ['History'],
        'Skinning/Interface': ['Interface'],
        'Skinning/osu!': ['osu!'],
        'Skinning/osu!catch': ['osu!catch'],
        'Skinning/osu!mania': ['osu!mania'],
        'Skinning/osu!taiko': ['osu!taiko'],
        'Skinning/skin.ini': ['skin.ini'],
        'Skinning/skin.ini/Blank': ['Blank'],
        'Skinning/Sounds': ['Sounds'],
        'Staff_Log': ['Staff log'],
        'Staff_Log/2014': ['2014'],
        'Staff_Log/2015': ['2015'],
        'Staff_Log/2016': ['2016'],
        'Staff_Log/2017': ['2017'],
        'Staff_Log/2018': ['2018'],
        'Staff_Log/2019': ['2019'],
        'Staff_Log/2020': ['2020'],
        'Storyboard_Scripting': ['Storyboard scripting'],
        'Storyboard_Scripting/Audio': ['Audio'],
        'Storyboard_Scripting/Cheat_Sheet': ['Cheat sheet'],
        'Storyboard_Scripting/Commands': ['Commands'],
        'Storyboard_Scripting/Compound_Commands': ['Compound commands'],
        'Storyboard_Scripting/General_Rules': ['General rules'],
        'Storyboard_Scripting/Objects': ['Objects'],
        'Storyboard_Scripting/osu!_File_Toggles': ['osu! file toggles'],
        'Storyboard_Scripting/Shorthand': ['Shorthand'],
        'Storyboard_Scripting/Variables': ['Variables'],
        'Storyboarding': ['Storyboarding'],
        'Storyboards': ['Storyboards'],
        'Submission': ['Submission'],
        'Tournament_Drawings': ['Tournament drawings'],
        'Tournaments': ['Tournaments'],
        'Twitter': ['Twitter'],
        'Visual_Settings': ['Visual settings'],
        'Welcome': ['Welcome']
    };
}

// Begin table output for the PR description
console.log('| Old path | New base path | New title |');
console.log('| :-- | :-- | :-- |');

// Track article titles that don't match their base path name
const notMatching = [];

// Loop through all of the articles, starting with the deepest in the file tree
for (const article of Object.entries(articleInfo()).sort(sortArticles)) {
    const oldFullPath = join(wikiDir, article[0]);
    const newTitle = article[1][0];
    const newBasePath = article[1][1] !== undefined ? article[1][1] : newTitle.replace(/ /g, '_');
    const newFullPath = join(oldFullPath, '..', newBasePath);

    // Fix title in English article
    const articleContent = fs.readFileSync(join(oldFullPath, 'en.md'), 'utf8');
    const articleContentNewTitle = articleContent.replace(/^# .+?$/m, `# ${newTitle}`);
    fs.writeFileSync(join(oldFullPath, 'en.md'), articleContentNewTitle);

    // Throw errors if any paths or titles would change beyond capitalisation
    if (oldFullPath.toLowerCase() !== newFullPath.toLowerCase())
        console.error(article[0]);
    if ((articleContent.match(/^# (.+?)$/m) || [, ''])[1].toLowerCase() !== newTitle.toLowerCase())
        console.error(article[0]);

    // Output table row
    console.log(`| ${article[0]} | ${newBasePath} | ${newTitle} |`);

    // If the article title doesn't match the base path name, track it
    if (newBasePath !== newTitle.replace(/ /g, '_'))
        notMatching.push({ path: newBasePath, title: newTitle });

    // Rename folder
    fs.renameSync(oldFullPath, newFullPath);
}

// Output the not matching titles/paths
console.log();
console.log('| New base path | New title |');
console.log('| :-- | :-- |');
for (const pair of notMatching)
    console.log(`| ${pair.path} | ${pair.title} |`);
