#!/usr/bin/env node

const fs = require('fs');
const { join } = require('path');
const { loadGroup, groupMap, groupTranslation } = require('./include');

function updateTables(target, source) {
    const tableRegex = /^\|.+?\|$(?:\n$)?/gms;

    const targetMatches = target.match(tableRegex);
    const sourceMatches = source.match(tableRegex);

    if (targetMatches.length !== sourceMatches.length)
        return;


}

for (const group of Object.keys(groupMap)) {
    const en = loadGroup(group);

    for (const locale of ['fr', 'pl']) {
        const updated = updateTables(loadGroup(group, locale), en);
        fs.writeFileSync(join(__dirname, `../wiki/People/The_Team/${group}/${locale}.md`), updated);
    }
}
