#!/usr/bin/env node

const { existsSync } = require('fs');
const { join } = require('path');

function getOption(options, arg) {
    arg = arg.replace(/^-+|=.+$/g, '');
    const type = options[arg];

    if (type === undefined)
        return null;

    if (type.startsWith('='))
        return getOption(options, type.substring(1));

    return { name: arg, type };
}

function getOptions(command, args) {
    const options = {};
    const trySetOption = (arg, canShift) => {
        const option = getOption(command.options, arg);

        if (option === null) {
            console.error(`Invalid option "${arg}". Type "wiki ${commandName} --help" for help.`);
            process.exit(1);
        }

        const value = option.type === 'boolean' || canShift && args.shift();

        if (!value) {
            console.error(`Option "${arg}" requires a value. Type "wiki ${commandName} --help" for help.`);
            process.exit(1);
        }

        options[option.name] = value;
    }

    while (args.length > 0 && args[0].startsWith('-')) {
        const arg0 = args.shift();

        if (arg0 === '-' || arg0 === '--')
            break;

        if (arg0[1] === '-')
            trySetOption(arg0, true);
        else {
            for (let i = 1; i < arg0.length - 1; ++i)
                trySetOption(`-${arg0[i]}`, false);

            trySetOption(`-${arg0[arg0.length - 1]}`, true);
        }
    }

    options._ = args;
    return options;
}

const commandName = process.argv[2] || 'help';

if (!existsSync(join(__dirname, `wiki-${commandName}.js`))) {
    console.error(`Invalid command "${commandName}". Type "wiki help" for help.`);
    process.exit(1);
}

const command = require(`./wiki-${commandName}`);

if (command.options === undefined)
    command.options = {};

command.options.h = '=help';
command.options.help = 'boolean';
command.run(getOptions(command, process.argv.slice(3)));
